### ISSUE TITLE
This module does not compile when you're using Almond for packaging

### ISSUE THREAD

**Issue by qbunt** [thomaswelton/requirejs-google-analytics#12]
[Almond](https://github.com/jrburke/almond) does not work with your package's internal shim. Almond cannot load external, remote dependencies. This makes it fail on compile when you're using Almond with require. Not suggesting you should change this, but possibly add a note in your docs that this shims itself in your require configuration. Otherwise, great work! :+1:

**Comment by metalshark** [comment]
Thanks Jeremy.

Will need to contact the Almond team and see if there is anything we can do
(like a comment or similar) to flag that it is to be loaded dynamically,
not statically during compile time.

**Comment by thomaswelton** [comment]
Almond also only allows one `requirejs.config` call.
When I made this package it was designed to use two `requirejs.config` config calls. One from a static `config.js` file and another within a script tag where the GA ID is injected from PHP.

So I don't think you'd really be able to use this with almond.

**Comment by qbunt** [comment]
@thomaswelton that's a fair point, I'm going to close this out. Seems to be more common knowledge than I realized that Almond doesn't support remote scripts, and seems like a really massive shortcoming. Thanks for rapping on this, I appreciate it!

**Comment by thomaswelton** [comment]
Just incase you didn't know, it is still possible to make an optimised build such that all you scripts (including requirejs) are optimised into one file. This is similar to an almond build but results in a larger built file as almond is smaller than requirejs.

Add `name: "requirejs"` to your build config and requirejs will be concatenated with your built main file. That way you will only have to load one script instead of requirejs + built file

**Comment by qbunt** [comment]
That was sort of the goal anyhow, we were on a crazy accelerated timeline.

The configuration for this build fell out of the thorax-generator for Yeoman and the way it had Almond set up. It was a compromise that we shouldn't really have made. For remote scripts we ended up loading them asynchronously as the things we need (Facebook, Instagram, Pinterest, GA, etc) are all designed that way. It adds a little risk but makes the build far smaller, and then we also know exactly what we're shipping out.

Thanks for the tip @thomaswelton. Dependency management is a hot topic of discussion, lots of people tooting the Browserify horn.
