### ISSUE TITLE
Event emitter dependency conflict

### ISSUE THREAD

**Issue by at0g** [thomaswelton/requirejs-google-analytics#3]
Hello, I've noticed a dependency conflict when installing this lib with bower alongside other projects (imagesloaded) that also use event emitter.

There is a full description of the issue here with steps to reproduce.
https://github.com/desandro/imagesloaded/issues/104

Could you please have a read and throw in your five cents.

Thanks

**Comment by thomaswelton** [comment]
I can see why you are having this issue. My event emitter dependency is not registered on the bower repo and does not have a unique name. Where as images loaded is using a different dependency registered with the same name in the bower registry.
Thanks for telling me. I never really know when people are using my stuff.

**Comment by at0g** [comment]
No problem, thanks for the GA plugin, I've used it a few times now.

**Comment by thomaswelton** [comment]
Totally untested, but 0.1.4 has been released. https://github.com/thomaswelton/requirejs-google-analytics/releases/tag/0.1.4
Turns out I already registered event-emitter in the bower registry. So updated the bower json to use that name.

And now problem :) would love to see some examples of where you used it.
Check out the new release and close the issue if it resolves the problem.

**Comment by thomaswelton** [comment]
Closed as per https://github.com/desandro/imagesloaded/issues/104

**Comment by at0g** [comment]
Thanks for the quick update.
Appears to work ok -> https://github.com/at0g/EEConflict

In the wild -> http://usandco.co.nz/ 
(hooked in to a marionette approuter)

The other projects are still private. Will send you a link when they're published =)

**Comment by thomaswelton** [comment]
Site looks awesome. And this issue was reported and fixed through github.com. Love how I can edit code and make new releases online :)

**Comment by at0g** [comment]
Thanks for the kind words. Github/Social coding FTW, everyone wins. 
Unlike the 2hrs it took to checkout an svn repo last night :/
