### ISSUE TITLE
Create Only Fields

### ISSUE THREAD

**Issue by metalshark** [thomaswelton/requirejs-google-analytics#4]
As per:
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference

"Create Only Fields
The following fields may only be set in the create method."

So in order to set these fields, they need to be available at time of creation.

To solve this, would you consider changing
`ga 'create', @config.id`
to:
`ga 'create', @config.id, @config.fields`
instead please?

**Comment by thomaswelton** [comment]
Moving flat today. If you need this a soon a PR would be welcomed.

**Comment by metalshark** [comment]
Before marking off version 0.1.5 there's a typo in README.md:

```
 ## Installation

-Instalation via bower
+Installation via bower
```

also make sure to set the version in bower.json and package.json (it got missed in version 0.1.4).

But nothing that can't wait until you've moved in!
