### ISSUE TITLE
Support for subdomains

### ISSUE THREAD

**Issue by binarykitchen** [thomaswelton/requirejs-google-analytics#6]
Hello there

This is a great library but I wonder how I can split GA tracking among subdomains?

I mean, we develop a huge website here and run it through different test stages, aka subdomains:

https://dev.oursite.com
https://staging.oursite.com
https://www.oursite.com

How can I deal with this inside requirejs-google-analytics where we have the same code? Any chance we can pass a different ACCOUNT_ID for each subdomain outside of the requirejs config?

**Comment by thomaswelton** [comment]
Right now you can only pass it in via the RJS config.
But previously I'd had some code in my HTML template that will conditionally include an inline script block that defines RJS config parameters where needed.
Also I don't have my RJS config served as a flat file, it's generated dynamically by the server so that I can pass in environment specific settings like this.

**Comment by binarykitchen** [comment]
I understand. Do you mean, each subdomain needs a different ACCOUNT_ID?

And can you show me how you are generating the RJS config file dynamically. With a grunt task?

**Comment by binarykitchen** [comment]
@thomaswelton I think this can be solved by defining a domain name `_setDomainName`, see http://www.ericmobley.net/guide-to-tracking-multiple-subdomains-in-google-analytics/

Can this be added?

**Comment by thomaswelton** [comment]
Probably. 
If you wanna fork me and submit a pr then that's cool. 
But right now I've gone freelance and not using this project so doubt I'll be able to add it.

**Comment by metalshark** [comment]
There is already support built in for this. You are referencing documentation for the old style tracker. This is https://developers.google.com/analytics/devguides/collection/analyticsjs/

You can use https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#cookieDomain and https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#legacyCookieDomain. both are create only fields so please refer to https://github.com/thomaswelton/requirejs-google-analytics#create-only-fields.

**Comment by binarykitchen** [comment]
Cookie domains? I think my request has nothing to do with cookies. All I want is to send separate data to GA for each sub domain. Or are you saying, GA works solely with cookies?

**Comment by metalshark** [comment]
There is already support for multiple account IDs:

https://github.com/thomaswelton/requirejs-google-analytics#ganewtrackerconfig

https://github.com/thomaswelton/requirejs-google-analytics/blob/master/test/spec/test.coffee#L23

you create one by passing in a new config calling `GA.newTracker(config)`. Pass in a new account ID.

`var mySubDomainTracker = GA.newTracker({'id': 'ACCOUNT_ID', 'fields': {'name': 'subDomainTracker'}});`

Then use `mySubDomainTracker` like you would `GA`.

Remember to read: https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced#multipletrackers especially the bit about using the `name` create only field.

Cookie domains is what `_setDomainName` used to do.

**Comment by binarykitchen** [comment]
Great, I see now how this works! I nailed it. All good, many thanks for your good help.

**Comment by binarykitchen** [comment]
Hmmm, I am sorry there is one more issue. When I create a new tracker for the sub domain, I can see that two trackers are still used whereas I only need one. To avoid unnecessary traffic I tried this in the require.config.js:

``` js
var gaId = 'UA-46775653-';

if (window.PRODUCTION)
    gaId += '3';

else if (window.STAGING)
    gaId += '2';

else
    gaId += '1';

requirejs.config({
    baseUrl: '/scripts',
    config: {
        'GA': {
            'id': gaId,
            'fields': {
                'forceSSL': true
            }
        }
    },
    ...
```

This works well on run time and the conditional configuration of the ID works well depending on the environment I am in.

Unfortunately this does not work when I minify the whole JS shebang via grunt with grunt's requirejs plugin:

```
Error: Error: The config in mainConfigFile /home/michael.heuberger/projects/binarykitchen/code/signdna/client/scripts/config/require.config.js cannot be used because it cannot be evaluated correctly while running in the optimizer. Try only using a config that is also valid JSON, or do not use mainConfigFile and instead copy the config values needed into a build file or command line arguments given to the optimizer.
```

I understand, it wants a static JSON. Makes sense.

I think I have an idea how to fix this. In https://github.com/thomaswelton/requirejs-google-analytics/blob/master/dist/GoogleAnalytics.js#L182 you are automatically creating an GoogleAnalytics instance. I think I would prefer to make the instance myself so that I have a chance to pass on the configuration on run time myself.

Something like this:

``` js
var gaId = 'UA-46775653-';

if (window.PRODUCTION)
    gaId += '3';

else if (window.STAGING)
    gaId += '2';

else
    gaId += '1';

new GoogleAnalytics({
    'id': gaId,
    'fields': {
        'forceSSL': true
    }
});
```

**Comment by binarykitchen** [comment]
PS: At the same time I asked at https://github.com/gruntjs/grunt-contrib-requirejs/issues/56 whether I can pass Grunt the gaId on runtime. Either way, one of these suggestions will work.

**Comment by metalshark** [comment]
You can call `requirejs.config` more than once. Be warning that changing values at runtime is what causes `findNestedDependencies: true` to fail so if I were you I'd write:

```
var gaId = 'UA-46775653-';

if (window.PRODUCTION)
    requirejs.config({
        config: {
            'GA': {
                'id': 'accno1',
    ...
else if (window.STAGING)
    requirejs.config({
        config: {
            'GA': {
                'id': 'accno2',
    ...
else
    requirejs.config({
        config: {
            'GA': {
                'id': 'accno3',
    ...
```

Then define the rest of requirejs.config elsewhere.

**Comment by binarykitchen** [comment]
@metalshark Thanks but sorry, that's a no-go for me. Too much code duplication. There must be a better solution out there!

**Comment by binarykitchen** [comment]
Solved with a second `config()` call, see https://github.com/jrburke/r.js/issues/599#issuecomment-31708054

Closed!
