### ISSUE TITLE
Shim `ga` is messing with RequireJS

### ISSUE THREAD

**Issue by binarykitchen** [thomaswelton/requirejs-google-analytics#7]
Hi again

It seems that I am unable to load your lib via RequireJS. It always says that the file `ga.js` cannot be found. There is no such file at all here. Why it is looking for `ga.js` then?

Here the error from grunt's requirejs task:

```
Error: ENOENT, no such file or directory '/Users/mick/projects/signdna/client/scripts/ga.js'
In module tree:
    main

{ [Error: Error: ENOENT, no such file or directory '/Users/mick/projects/signdna/client/scripts/ga.js'
In module tree:
    main

    at Object.fs.openSync (fs.js:427:18)
]
  originalError:
   { [Error: ENOENT, no such file or directory '/Users/mick/projects/signdna/client/scripts/ga.js']
     errno: 34,
     code: 'ENOENT',
     path: '/Users/mick/projects/signdna/client/scripts/ga.js',
     syscall: 'open',
     fileName: '/Users/mick/projects/signdna/client/scripts/ga.js',
     moduleTree: [ 'main' ] } }
```

Since `ga` is mentioned in the shim at https://github.com/thomaswelton/requirejs-google-analytics/blob/master/dist/GoogleAnalytics.js#L14 I suspect it has something to do with this.

In my requirejs config I have this line

``` js
'use strict';

requirejs.config({
    baseUrl: '/scripts',
    config: {
        'GA': {
            'id': 'UA-46775653-1'
        }
    },
    paths: {
        'requireLib': 'vendor/requirejs/require',

        'GA': 'vendor/requirejs-google-analytics/dist/GoogleAnalytics'
    },
    include: [
        "requireLib"
    ]
});
```

and in the main file I have this:

``` js
require([
    'config/require.config',
    'GA',
    'router',
], function(config, GA, router) {

    ...

    GA.ready(function(ga) {
        router.dispatch();
    });
});
```

Either it is a bug on your side or I am doing something wrong here. Can you help me?

Thanks!

**Comment by binarykitchen** [comment]
And in grunt-contrib-requirejs I have this config

``` js
        // here are lots of interesting grunt-contrib-requirejs options:
        // https://github.com/jrburke/r.js/blob/master/build/example.build.js
        requirejs: {
            js: {
                options: {
                    findNestedDependencies: true,
                    baseUrl: "client/scripts",
                    name: 'main',
                    mainConfigFile: "client/scripts/config/require.config.js",
                    out: "server/public/scripts/main.min.js",
                    useStrict: true,
                    preserveLicenseComments: false,
                    optimize: 'uglify2',
                    pragmasOnSave: {
                        excludeJade: true // remove jade compiler, see https://github.com/deedubs/require-jade
                    }
                }
            },
            ...
}
```

**Comment by binarykitchen** [comment]
If I add in the grunt-contrib-requirejs config these parameters then it works:

```
                    paths: {
                      'ga': '//www.google-analytics.com/analytics'
                    },
                    shim: {
                      'ga': {
                        exports: 'ga'
                      }
                    },
```

But grunt prints a new warning:

```
>> Cannot optimize network URL, skipping:
>> //www.google-analytics.com/analytics.js
```

**Comment by metalshark** [comment]
Are you using r.js?

**Comment by binarykitchen** [comment]
@metalshark Yep

**Comment by metalshark** [comment]
@binarykitchen will look into these two issues this evening - expect a solution within 24 hours

**Comment by metalshark** [comment]
I cannot reproduce this and added r.js to the project as it is worth testing for. Does this work on your system and in which case can you help pin point the issue?

**Comment by metalshark** [comment]
This is due to the way `findNestedDependencies: true` operates and is beyond our control. Try `findNestedDependencies: false` instead for now.

**Comment by metalshark** [comment]
This option is not turned on by default due to issues with dynamic/runtime requirements, such as this.
https://github.com/jrburke/r.js/blob/master/build/example.build.js#L320

**Comment by metalshark** [comment]
Have a found a workaround so this is fixed in version 0.1.8 now.

**Comment by metalshark** [comment]
Reverted the change in 0.1.9 as it breaks the plugin actually working.

**Comment by binarykitchen** [comment]
Thanks. But let me double check: version 0.1.9 does not change anything, correct?

**Comment by metalshark** [comment]
0.1.9 just undoes the fix for `findNestedDependencies: true` as it causes other issues.

**Comment by binarykitchen** [comment]
I see. In that case nothing has changed for me yet. Thx anyway.

**Comment by binarykitchen** [comment]
@metalshark If you read jburke's comment at https://github.com/jrburke/r.js/issues/596#issuecomment-31631344 confirms that the use of shims is making everything more complicated.

I think if you can somehow get rid off shims in that lib, then it'll be much easier to use your library for everybody else.

Alternatively,  like @jburke said: _"I would suggest in the readme for a dependency that needed this kind of config, a suggestion to the consumer of the code of what type of config to insert into their project for it to work effectively."_

**Comment by metalshark** [comment]
Part of the whole beauty of this package is the dynamic shim and central
config. Think this is an edge case for this package. As stated in the code:

Load Google Analyticshttps://developers.google.com/analytics/devguides/collection/analyticsjs/
using
requirejs. Feel free to just use this snippet for a lightweight
implementation.
(sorry am using a smartphone so cannot link directly). You may be better
off with just the shim in your main config and talking to Google Analytics
directly.

This could be packaged up as just a convenience API, but this removes a
major advantage of ease-of-use.

@thomaswelton what are your thoughts?

**Comment by binarykitchen** [comment]
Yeah @metalshark, maybe I am better off using the raw analytics.js snippet instead of your library. Too many issues sorry.

But before I make this move, I am keen to read @thomaswelton 's opinion as well.

**Comment by binarykitchen** [comment]
Hey @metalshark there is a wrong bower version!
https://github.com/thomaswelton/requirejs-google-analytics/blob/master/bower.json#L3

Upon `bower install` I get this error:

```
bower requirejs-google-analytics#0.1.9         mismatch Version declared in the json (0.1.6) is different than the resolved one (0.1.9)
```

Be careful when making those changes ;)

**Comment by metalshark** [comment]
Ah, as you use David http://david-dm.org for the project I assumed you
wanted the latest dependencies. Running npm install will resolve.

**Comment by binarykitchen** [comment]
I do not use David. Why should I?

And still, the version number in bower.json is wrong. Why don't you want to increment it? Also, bower and npm aren't related at all so I doubt that `npm install` will help.

**Comment by metalshark** [comment]
Good spot - my bad - that was me getting the wrong end of the stick.

Must stop using a smartphone to view github.

**Comment by binarykitchen** [comment]
hehe :)
